target_default: 50_lake_biogeochem_model

include:
  - 40_constituent_load_model.yml

packages:
  - deSolve
  - LakeMetabolizer
  - snow
  - sp
  - rgeos
  - parallel
  - rgdal
  - maptools
  - AquaEnv
  - marelac
  - yaml

sources:
  - ../50_lake_biogeochem_model/src/LakeBiogeochem.R # change to actual name

include: 
  - 50_lake_biogeochem_model.yml

targets:
  all:
    depends: 60_results/code/figure_01.png
